import type { RawCollection } from '@directus/types';

export const AppSecretsCollection: RawCollection = {
	collection: 'app_secrets',
	meta: {
		hidden: true,
		icon: 'shield_lock',
	},
	schema: { schema: 'public', name: 'app_secrets', comment: null },
	fields: [
		{
			field: 'type',
			type: 'string',
			schema: {
				name: 'type',
				table: 'app_secrets',
				data_type: 'character varying',
				default_value: null,
				generation_expression: null,
				max_length: 255,
				numeric_precision: null,
				numeric_scale: null,
				is_generated: false,
				is_nullable: true,
				is_unique: false,
				is_indexed: false,
				is_primary_key: false,
				has_auto_increment: false,
				foreign_key_schema: null,
				foreign_key_table: null,
				foreign_key_column: null,
				comment: null,
			},
			meta: {
				field: 'type',
				special: null,
				interface: 'select-dropdown',
				options: [Object],
				display: null,
				display_options: null,
				readonly: true,
				hidden: false,
				width: 'full',
				translations: null,
				note: null,
				conditions: null,
				required: false,
				group: null,
				validation: null,
				validation_message: null,
				searchable: false,
			},
		},
		{
			field: 'name',
			type: 'string',
			schema: {
				name: 'name',
				data_type: 'character varying',
				default_value: null,
				generation_expression: null,
				max_length: 255,
				numeric_precision: null,
				numeric_scale: null,
				is_generated: false,
				is_nullable: true,
				is_unique: false,
				is_indexed: false,
				is_primary_key: false,
				has_auto_increment: false,
				foreign_key_schema: null,
				foreign_key_table: null,
				foreign_key_column: null,
				comment: null,
			},
			meta: {
				field: 'name',
				special: null,
				interface: 'input',
				options: null,
				display: null,
				display_options: null,
				readonly: true,
				hidden: false,
				width: 'full',
				translations: null,
				note: null,
				conditions: null,
				required: true,
				group: null,
				validation: null,
				validation_message: null,
				searchable: true,
			},
		},
		{
			field: 'fields',
			type: 'json',
			schema: {
				name: 'fields',
				table: 'app_secrets',
				data_type: 'json',
				default_value: null,
				generation_expression: null,
				max_length: null,
				numeric_precision: null,
				numeric_scale: null,
				is_generated: false,
				is_nullable: true,
				is_unique: false,
				is_indexed: false,
				is_primary_key: false,
				has_auto_increment: false,
				foreign_key_schema: null,
				foreign_key_table: null,
				foreign_key_column: null,
				comment: null,
			},
			meta: {
				field: 'fields',
				special: null,
				interface: 'input-code',
				display: null,
				display_options: null,
				readonly: true,
				hidden: false,
				width: 'full',
				translations: null,
				note: null,
				conditions: null,
				required: false,
				group: null,
				validation: null,
				validation_message: null,
				searchable: false,
			},
		},
	],
};
